nodes:
  - {x: -2, y: 10.5}
  - {x: 6, y: 10.5}
  - {x: 2, y: 7.5}
  - {x: -6, y: 7.5}
  - {x: -2, y: 4.5}
  - {x: 6, y: 4.5}
  - {x: 2, y: 1.5}
  - {x: -6, y: 1.5}
  - {x: -2, y: -1.5}
  - {x: 6, y: -1.5}
  - {x: 2, y: -4.5}
  - {x: -6, y: -4.5}
  - {x: -2, y: -7.5}
  - {x: 6, y: -7.5}
  - {x: 2, y: -10.5}
  - {x: -6, y: -10.5}
